language: node_js
dist: trusty
node_js: stable
sudo: required

env:
  - NODE_ENV=development BABEL_ENV=development
install:
  - npm install -g truffle@4.1.13 solc
  - npm install
script:
  - truffle version
  - truffle compile
  - npm run build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: build_webpack/
  on:
  branch: master
